######################################################################
# Automatically generated by qmake (2.01a) mar. juil. 1 14:39:56 2008
######################################################################

TEMPLATE = app
TARGET = geshi2qnfa 

QT -= gui
QT += xml

DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp

